### ISSUE TITLE
Git color in tree view does not work

### ISSUE THREAD

**Issue by wyudong** [saadq/bliss-ui#1]
Git color won't show if using bliss-ui, other default ui are fine. Don't know if it's a bug or not.

Thanks for creating bliss-ui. Cheers!

**Comment by saadq** [comment]
Hey @wyudong, thanks for raising this issue! This was actually an intentional choice when this theme had just been for my own personal use and wanted to keep the look very minimal. The styles for this are here:

https://github.com/saadq/bliss-ui/blob/86871f01c937fe705e90d1abfcc498c543c44f45/styles/tree-view.less#L6-L23

However, I understand that people may not like this choice, so it may make sense to remove these styles from the theme, and maybe just put **Recommended Styles** in the README and move the styles there.

Would you like to send a PR? Just let me know, otherwise I can make the change myself within a couple of days.

**Comment by wyudong** [comment]
Hi @saadq I find I need to comment these lines as well in order to enable git color:

https://github.com/saadq/bliss-ui/blob/86871f01c937fe705e90d1abfcc498c543c44f45/styles/tree-view.less#L54-L56

PR #2

**Comment by saadq** [comment]
Ah, thanks for finding that, and just gave a quick comment to your PR

**Comment by wyudong** [comment]
To remove code about `.icon-file-text, .icon` occurs a side effect, that is when selecting any item in a folder which already has files being modified, all the other items will turn yellow (the modified color). I don't know the reason. Will have a look at it later.

![git](https://user-images.githubusercontent.com/5687273/31048366-29280b52-a64e-11e7-9e52-9090dd1ee400.gif)

**Comment by saadq** [comment]
Oh very strange, I'll try to take a look later as well in case you don't see any immediate cause.

**Comment by wyudong** [comment]
@saadq any progress from your side?

**Comment by wyudong** [comment]
@saadq I think I've fixed it. Testing it now and will make a pr if everything's good.

**Comment by saadq** [comment]
Sorry for the delay! I had some things going on so wasn't able to work on it. Checking out your PR right now!
