### ISSUE TITLE
Not Compatible with Latest Atom (git diff changes)

### ISSUE THREAD

**Issue by framerate** [saadq/bliss-ui#6]
Is this UI abandoned?

I took a stab at fixing it but I'm not a theme coder so I couldn't seem to make it look right!

More info here: https://github.com/atom/github/issues/1911

Just wondering if this is ever going to be updated or if I should take it over. Thanks!

**Comment by saadq** [comment]
No, it isn't abandoned although I haven't done much for it lately. I'll look into this and fix it soon!

**Comment by framerate** [comment]
Awesome!! It's not a hard fix I don't think. The info seemed like mostly
new class names but apparently they had never seen someone customize the
diff stuff as much as you did. :)

Make sure to check what they said on the arpk repo and let me know if I can
help on the code side!

**Comment by saadq** [comment]
Great, should be able to push a fix by today then. I'll keep you posted here

**Comment by saadq** [comment]
This should be fixed in the latest version of `bliss-syntax`. It seems as though I have most of the git diff styling there. Please try upgrading `bliss-syntax` and let me know what you think.

**No selection:**
<img width="1440" alt="screen shot 2019-03-06 at 12 09 08 am" src="https://user-images.githubusercontent.com/5678694/53857639-0e163180-3fa5-11e9-949a-017105aead1e.png">

**Added selection:**
<img width="1440" alt="screen shot 2019-03-06 at 12 09 12 am" src="https://user-images.githubusercontent.com/5678694/53857640-0e163180-3fa5-11e9-929d-810ee37b05ab.png">

**Deleted selection:**
<img width="1440" alt="screen shot 2019-03-06 at 12 09 15 am" src="https://user-images.githubusercontent.com/5678694/53857641-0e163180-3fa5-11e9-8d63-aa426691fceb.png">

**Hunk selection:**
<img width="1440" alt="screen shot 2019-03-06 at 12 09 19 am" src="https://user-images.githubusercontent.com/5678694/53857642-0e163180-3fa5-11e9-839a-79e2eb2c0565.png">

If anything still feels off, feel free to reopen this issue.

**Comment by framerate** [comment]
You're my hero dude. I'll check it out tomorrow!

**Comment by framerate** [comment]
I know it's a syntax thing but I wanted to keep the convo here. Not sure if you saw this with the latest deploy:

(1 deprecation)
![image](https://user-images.githubusercontent.com/74291/53912558-0b9bf200-400e-11e9-9377-bcb66c9fc50c.png)

**Comment by saadq** [comment]
Thanks for reporting, I'll look into it once I get home

**Comment by saadq** [comment]
Should be fixed as of v0.3.6. Thanks again @framerate! Also feel free to just open new issues in either repo as it makes it a bit easier to track stuff.

**Comment by framerate** [comment]
Will do! looks good! Thanks @saadq You're a badass!
